version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: ct-kings-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ct-kings-pg
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ct-kings-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ct-kings-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ctkings.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - ct-kings-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  ct-kings-network:
    driver: bridge 